<ul id="nav">
  <li><a href="http://www.mozilla.org/projects/calendar/"><strong>Calendar Project</strong></a>
    <ul>
      <li><a href="http://www.mozilla.org/projects/calendar/about.html">About the Team</a></li>
      <li><a href="http://www.google.com/calendar/ical/u7pke58sc91ksbm4h9pf9ofe8c%40group.calendar.google.com/public/basic.ics">Project Calendar<br>(iCalendar file)</a></li>
      <li><a href="http://weblogs.mozillazine.org/calendar">Developers blog</a></li>
      <li><a href="http://www.mozilla.org/projects/calendar/help.html">Help Us</a></li>
      <li><a href="http://www.mozilla.org/projects/calendar/bugs.html">Bugs</a></li>
      <li><a href="http://wiki.mozilla.org/Calendar:Dev_Guide">Developer Guide</a></li>
    </ul>
  </li>
  <li><a href="http://www.mozilla.org/projects/calendar/lightning/"><strong>Lightning</strong></a></li>
  <li><a href="http://www.mozilla.org/projects/calendar/sunbird/"><strong>Mozilla Sunbird&reg;</strong></a></li>
  <li><a><strong>Docs &amp; Extras</strong></a>
    <ul>
      <li><a href="http://www.mozilla.org/projects/calendar/faq.html">FAQs</a></li>
      <li><a href="http://www.mozilla.org/projects/calendar/holidays.html">Holiday Calendars</a></li>
      <li><a href="http://www.mozilla.org/projects/calendar/links.html">Useful Links</a></li>
    </ul>
  </li>
</ul>
