<ul id="nav">
  <li><a href="../"><strong>Calendar Project</strong></a></li>
  <li><a href="./"><strong>Lightning</strong></a>
    <ul>
      <li><a href="download.html">Download Lightning</a></li>
      <li><a href="build.html">Build Lightning</a></li>
    </ul>
  </li>
  <li><a href="../sunbird/"><strong>Mozilla Sunbird&reg;</strong></a></li>
  <li><a><strong>Docs &amp; Extras</strong></a>
    <ul>
      <li><a href="../faq.html">FAQs</a></li>
      <li><a href="../holidays.html">Holiday Calendars</a></li>
      <li><a href="../links.html">Useful Links</a></li>
    </ul>
  </li>
</ul>
