#!/bin/csh -f

set pull_time=$1
set rotate_time=$2 
set test_url=pagelist.html

echo '<head>' > $test_url


echo '<title>browser buster test pages</title>' >> $test_url
echo '</head>' >> $test_url
echo '<body>' >> $test_url

echo '<h1>Browser Buster Test Pages</h1>' >> $test_url

echo 'Last updated:' `date` >> $test_url
echo '<OL>' >> $test_url

foreach url ( `ls -1 */url.* | sort -n -t . +1` )

#  echo '<LI> <a href="'`cat $url`'">'`echo $url` \: `cat $url` '</a>' 
 echo '<LI> <a href="'`cat $url`'" TARGET=test_win>'`echo $url` \: `cat $url` '</a>' >> $test_url
end
echo '</OL>' >> $test_url


 echo '<h1>More Browser Buster Test Pages</h1>' >> $test_url
 echo 'These are additional "interesting" pages not part of the automated test pages cycle' >> $test_url
 echo 'due to the fact they are on unreliable servers, ' >> $test_url
 echo 'are known crashers, or interupt with the operation of the test. ' >> $test_url

echo '<OL>' >> $test_url

foreach url ( `ls -1 */*.url | sort -n -t . +1` )

 # echo '<LI> <a href="'`cat $url`'">'`echo $url` \: `cat $url` '</a>' 
 echo '<LI> <a href="'`cat $url`'" TARGET=test>'`echo $url` \: `cat $url` '</a>' >> $test_url
end
echo '</OL>' >> $test_url

 echo '</body>' >> $test_url


