   </span>
   <span class="status">
    <span class="downloads">Downloads: <span>12</span></span>
    <span class="goal">Goal: <span>600,000,000</span></span>
   </span>
  </p>
  <div class="common"><div>
   <div class="todo">
    <h2>Promote</h2>
    <ol>
     <li><a href="/promote/01.html" id="n1">Convert people</a></li>
     <li><a href="../webads/" id="n2">Advertise on site</a></li>
     <li><a href="../blog/" id="n3">Blog weekly</a></li>
     <li><a href="/promote/04.html" id="n4">Advertise in AIM</a></li>
     <li><a href="../submit/#ideas" id="n5">Share your ideas!</a></li>
    </ol>
   </div>
   <div class="affiliates">
    <form>
     <h2>Affiliates</h2>
     <p class="login">
      <label><span>E-mail address:</span> <span><input type="text" name="user"></span></label>
      <label><span>Password:</span> <span><input type="password" name="password"></span></label>
      <input type="submit" value="Login">
     </p>
     <p class="register">
      No account?
      <a href="/register.html">Register</a>
     </p>
    </form>
   </div>
  </div></div>
  <div class="content">