#!/bin/sh

LPATH='-L/group/jlnance/tmp/lib -L/group/jlnance/tmp/src/bm/dist/lib'
TPLIBS='libIDL.so libgmodule.so libgdk.so libgthread.so libglib.so libgtk.so'
PROG=dist/bin/apprunner
LIBDIR='-shlibdir /group/jlnance/tmp/atomlibs'
ECHO=echo

PLIBS=""
for xx in $TPLIBS; do
    PLIBS="$PLIBS -incobj $xx"
done

for xx in /group/jlnance/tmp/src/bm/dist/lib/lib*.so; do
    lbase=`basename $xx`
    PLIBS="$PLIBS -incobj $lbase"
done

$ECHO /bin/gprof -all $PLIBS
