#!/bin/sh

LPATH='-L/group/jlnance/tmp/lib -L/group/jlnance/tmp/src/bm/dist/lib'
TPLIBS='libIDL.so libgmodule.so libgdk.so libgthread.so libglib.so libgtk.so'
PROG=dist/bin/apprunner
LIBDIR='-shlibdir /group/jlnance/tmp/atomlibs'
TOOLARGS='-toolargs="-calltime -threads"'

PLIBS=""
for xx in $TPLIBS; do
    PLIBS="$PLIBS -incobj $xx"
done

for xx in /group/jlnance/tmp/src/bm/dist/lib/lib*.so; do
    lbase=`basename $xx`
    PLIBS="$PLIBS -incobj $lbase"
done

$ECHO atom $PROG -o $PROG.hiprof -tool hiprof -env threads -toolargs="-calltime -threads" $LIBDIR -all $LPATH $PLIBS
