<ul id="nav">
  <li><a href="../"><strong>Calendar Project</strong></a></li>
  <li><a href="../lightning/"><strong>Lightning</strong></a></li>
  <li><a href="./"><strong>Mozilla Sunbird&reg;</strong></a>
    <ul>
      <li><a href="download.html">Download Sunbird</a></li>
      <li><a href="l10n_download.html">International Downloads</a></li>
      <li><a href="screenshot.html">Sunbird Screenshots</a></li>
      <li><a href="build.html">Build Sunbird</a></li>
    </ul>
  </li>
  <li><a><strong>Docs &amp; Extras</strong></a>
    <ul>
      <li><a href="../faq.html">FAQs</a></li>
      <li><a href="../holidays.html">Holiday Calendars</a></li>
      <li><a href="../links.html">Useful Links</a></li>
    </ul>
  </li>
</ul>
